In [2]:
from input.dataset.util.util import DatasetUtil

X, y = DatasetUtil.load_X_y_tensor_datasets(include_trailer=False)
X[:1, :]

2023-09-18 11:16:56.979415: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-18 11:16:57.014052: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-18 11:16:57.147796: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-18 11:16:57.148515: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-18 11:16:57.920477: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

<tf.Tensor: shape=(1, 28), dtype=float32, numpy=
array([[5.1084e+04, 6.6205e+04, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 6.2133e-01, 2.1420e+03, 2.0070e+03,
        0.0000e+00, 1.0000e+00, 1.0000e+00]], dtype=float32)>

In [3]:
from utils.utils import BASE_TF_DATA
from utils.constants import DEV

dataset = DatasetUtil.load_dataset(DEV, BASE_TF_DATA)
dataset.take(1)

<_TakeDataset element_spec=({'movie_features': TensorSpec(shape=(24,), dtype=tf.float32, name=None), 'movie_ids': TensorSpec(shape=(), dtype=tf.float32, name=None), 'user_ids': TensorSpec(shape=(), dtype=tf.float32, name=None), 'user_context': TensorSpec(shape=(2,), dtype=tf.float32, name=None)}, TensorSpec(shape=(), dtype=tf.float32, name=None))>

In [4]:
from input.dataset.preprocess.dataset_with_trailer_data.trailer_dataset_path_util import \
    get_path_to_trailer_dataset_tensor

X, y = DatasetUtil.load_X_y_tensor_datasets(include_trailer=True,path=get_path_to_trailer_dataset_tensor("max", "pca"))
X[:1, :]

<tf.Tensor: shape=(1, 148), dtype=float32, numpy=
array([[ 5.1084000e+04,  6.6205000e+04,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  1.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  1.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  6.2133002e-01,  2.1420000e+03,
         2.0070000e+03,  0.0000000e+00,  1.0000000e+00,  1.0000000e+00,
        -2.0273091e-01,  9.5523708e-02, -1.2771620e-01,  8.2465366e-02,
        -1.6473647e-02, -3.9859116e-02, -2.5076721e-02, -5.0548602e-02,
         1.8137518e-01,  2.9489623e-02,  4.7989987e-02,  9.0243192e-03,
         4.6561722e-02,  1.5344238e-01, -9.5781952e-02, -2.4961164e-02,
         3.8902443e-02,  3.2553073e-02, -3.2949533e-02,  5.2681740e-02,
         5.1878247e-02,  1.8382192e-02,  4.4274952e-02,  1.7551666e-02,
         2.230

In [5]:
dataset = DatasetUtil.load_dataset(DEV, get_path_to_trailer_dataset_tensor("max", "pca"))
dataset.take(1)

NotFoundError: /home/teodora/Personal/Uni/isp_project/movie_recommendation_system/data/with_trailer/max_pca/tensor/dev/dataset_spec.pb; No such file or directory